import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "BadBug.studio",
    description: "Generated by create next app",
};

const Footer = () => {
  return (
    <footer className="w-full py-6 mt-auto">
      <div className="container mx-auto px-4 flex flex-col items-center justify-center">
        
        {/* ICP 备案 */}
        <a
          href="https://beian.miit.gov.cn/"
          target="_blank"
          rel="noopener noreferrer"
          className="text-[12px] text-neutral-500 hover:text-neutral-800 dark:hover:text-neutral-300 transition-colors duration-200 tracking-wide"
        >
          蜀ICP备2026023230号
        </a>

        {/* 版权信息 (可选) */}
        <p className="text-[9px] text-neutral-400">
          © {new Date().getFullYear()} BadBug. All rights reserved.
        </p>
        
      </div>
    </footer>
  );
};

// layout.tsx
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="zh-CN">
            <body className="flex flex-col font-sans antialiased">
                {/* flex-grow 让中间内容区域自动撑开，把 footer 顶到底部 */}
                <main className="grow">{children}</main>

                {/* 你的 Footer 组件 */}
                <Footer />
            </body>
        </html>
    );
}
