import type { Metadata } from "next";
import "./globals.css";

import Footer from "./components/layout/footer";

export const metadata: Metadata = {
    title: "BadBug.studio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="zh-CN">
            <head>
                {/* 注意这里 src 填的是我们刚才代理的本地路径 /stats/script.js */}
                <script
                    defer
                    src="https://analytics.badbug.studio/script.js"
                    data-website-id="f9d3ae60-764d-4845-9545-19954c27c51b"
                ></script>
            </head>
            <body className="flex flex-col font-sans antialiased">
                {/* flex-grow 让中间内容区域自动撑开，把 footer 顶到底部 */}
                <main className="grow">{children}</main>

                {/* 你的 Footer 组件 */}
                {/* <Footer /> */}
            </body>
        </html>
    );
}
